//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairMark.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FairMark.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Файл ИдФайл=&quot;ON_NSCHFDOPPRMARK_2LT-600061573_2LT-354_20191121_99933cc4-710d-4a6f-aa1c03203dc8f6c4&quot; ВерсФорм=&quot;5.01&quot; ВерсПрог=&quot;EDOLite 1.0&quot;&gt;
        ///   &lt;СвУчДокОбор ИдОтпр=&quot;2LT-600000078&quot; ИдПол=&quot;2LT-354&quot;&gt;
        ///      &lt;СвОЭДОтпр НаимОрг=&quot;ООО &apos;Оператор-ЦРПТ&apos;&quot; ИННЮЛ=&quot;00000000&quot; ИдЭДО=&quot;2LT&quot; /&gt;
        ///   &lt;/СвУчДокОбор&gt;
        ///   &lt;Документ КНД=&quot;1115131&quot; Функция=&quot;СЧФ&quot; ПоФактХЖ=&quot;Документ об отгрузке товаров (выполнении работ), передаче имущественных прав (документ об оказании услуг)&quot; НаимДокОпр=&quot;Счет- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EdoLite_Chapter_3_1_SampleUpd {
            get {
                return ResourceManager.GetString("EdoLite_Chapter_3_1_SampleUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot;?&gt;
        ///&lt;Файл ИдФайл=&quot;ON_KORSCHFDOPPR_2LT-600003352_2LT-600006439_20210426_a4941fa7-9a53-4991-aa02-f1606b71142c&quot; ВерсФорм=&quot;5.01&quot; ВерсПрог=&quot;EDOLite 1.0&quot;&gt;
        ///    &lt;СвУчДокОбор ИдОтпр=&quot;2LT-600006439&quot; ИдПол=&quot;2LT-600003352&quot;&gt;
        ///        &lt;СвОЭДОтпр НаимОрг=&quot;ООО &amp;quot;Оператор-ЦРПТ&amp;quot;&quot; ИННЮЛ=&quot;7731376812&quot; ИдЭДО=&quot;2LT&quot;/&gt;
        ///    &lt;/СвУчДокОбор&gt;
        ///    &lt;Документ КНД=&quot;1115127&quot; Функция=&quot;КСЧФДИС&quot; ПоФактХЖ=&quot;Документ об изменении стоимости отгруженных товаров (выполненных работ, оказанных услуг), п [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ON_KORSCHFDOPPR_2LT_600003352_2LT_600006439_20210426_a4941fa7_9a53_4991_aa02_f1606b71142c {
            get {
                return ResourceManager.GetString("ON_KORSCHFDOPPR_2LT_600003352_2LT_600006439_20210426_a4941fa7_9a53_4991_aa02_f160" +
                        "6b71142c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot;?&gt;
        ///&lt;Файл ИдФайл=&quot;ON_KORSCHFDOPPR_2LT-600006439_2LT-600003352_20210426_68426923-d1e2-4582-93f2-f690912d5161&quot; ВерсФорм=&quot;5.01&quot; ВерсПрог=&quot;EDOLite 1.0&quot;&gt;
        ///    &lt;СвУчДокОбор ИдОтпр=&quot;2LT-600003352&quot; ИдПол=&quot;2LT-600006439&quot;&gt;
        ///        &lt;СвОЭДОтпр НаимОрг=&quot;ООО &amp;quot;Оператор-ЦРПТ&amp;quot;&quot; ИННЮЛ=&quot;7731376812&quot; ИдЭДО=&quot;2LT&quot;/&gt;
        ///    &lt;/СвУчДокОбор&gt;
        ///    &lt;Документ КНД=&quot;1115127&quot; Функция=&quot;КСЧФДИС&quot; ПоФактХЖ=&quot;Документ об изменении стоимости отгруженных товаров (выполненных работ, оказанных услуг), п [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ON_KORSCHFDOPPR_2LT_600006439_2LT_600003352_20210426_68426923_d1e2_4582_93f2_f690912d5161 {
            get {
                return ResourceManager.GetString("ON_KORSCHFDOPPR_2LT_600006439_2LT_600003352_20210426_68426923_d1e2_4582_93f2_f690" +
                        "912d5161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot;?&gt;
        ///&lt;Файл ИдФайл=&quot;ON_NSCHFDOPPR_2LT-600003352_2LT-600006439_20210426_00c4d099-a48f-47ed-8608-54d32890fe73&quot; ВерсФорм=&quot;5.01&quot; ВерсПрог=&quot;EDOLite 1.0&quot;&gt;
        ///    &lt;СвУчДокОбор ИдОтпр=&quot;2LT-600006439&quot; ИдПол=&quot;2LT-600003352&quot;&gt;
        ///        &lt;СвОЭДОтпр НаимОрг=&quot;ООО &amp;quot;Оператор-ЦРПТ&amp;quot;&quot; ИННЮЛ=&quot;7731376812&quot; ИдЭДО=&quot;2LT&quot;/&gt;
        ///    &lt;/СвУчДокОбор&gt;
        ///    &lt;Документ КНД=&quot;1115131&quot; Функция=&quot;СЧФДОП&quot; ПоФактХЖ=&quot;Документ об отгрузке товаров (выполнении работ), передаче имущественных прав (документ об оказ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ON_NSCHFDOPPR_2LT_600003352_2LT_600006439_20210426_00c4d099_a48f_47ed_8608_54d32890fe73_УПДи {
            get {
                return ResourceManager.GetString("ON_NSCHFDOPPR_2LT_600003352_2LT_600006439_20210426_00c4d099_a48f_47ed_8608_54d328" +
                        "90fe73_УПДи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot;?&gt;
        ///&lt;Файл ИдФайл=&quot;ON_NSCHFDOPPR_2LT-600003352_2LT-600006439_20210426_afb6cce6-6cb9-4147-bc2f-689be4fd2198&quot; ВерсФорм=&quot;5.01&quot; ВерсПрог=&quot;EDOLite 1.0&quot;&gt;
        ///    &lt;СвУчДокОбор ИдОтпр=&quot;2LT-600006439&quot; ИдПол=&quot;2LT-600003352&quot;&gt;
        ///        &lt;СвОЭДОтпр НаимОрг=&quot;ООО &amp;quot;Оператор-ЦРПТ&amp;quot;&quot; ИННЮЛ=&quot;7731376812&quot; ИдЭДО=&quot;2LT&quot;/&gt;
        ///    &lt;/СвУчДокОбор&gt;
        ///    &lt;Документ КНД=&quot;1115131&quot; Функция=&quot;СЧФДОП&quot; ПоФактХЖ=&quot;Документ об отгрузке товаров (выполнении работ), передаче имущественных прав (документ об оказ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ON_NSCHFDOPPR_2LT_600003352_2LT_600006439_20210426_afb6cce6_6cb9_4147_bc2f_689be4fd2198 {
            get {
                return ResourceManager.GetString("ON_NSCHFDOPPR_2LT_600003352_2LT_600006439_20210426_afb6cce6_6cb9_4147_bc2f_689be4" +
                        "fd2198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot;?&gt;
        ///&lt;Файл ИдФайл=&quot;ON_NSCHFDOPPR_2LT-600006439_2LT-600003352_20210426_0dc17582-d11d-4a4d-8e25-816d59870ef4&quot; ВерсФорм=&quot;5.01&quot; ВерсПрог=&quot;EDOLite 1.0&quot;&gt;
        ///    &lt;СвУчДокОбор ИдОтпр=&quot;2LT-600003352&quot; ИдПол=&quot;2LT-600006439&quot;&gt;
        ///        &lt;СвОЭДОтпр НаимОрг=&quot;ООО &amp;quot;Оператор-ЦРПТ&amp;quot;&quot; ИННЮЛ=&quot;7731376812&quot; ИдЭДО=&quot;2LT&quot;/&gt;
        ///    &lt;/СвУчДокОбор&gt;
        ///    &lt;Документ КНД=&quot;1115131&quot; Функция=&quot;СЧФДОП&quot; ПоФактХЖ=&quot;Документ об отгрузке товаров (выполнении работ), передаче имущественных прав (документ об оказ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ON_NSCHFDOPPR_2LT_600006439_2LT_600003352_20210426_0dc17582_d11d_4a4d_8e25_816d59870ef4 {
            get {
                return ResourceManager.GetString("ON_NSCHFDOPPR_2LT_600006439_2LT_600003352_20210426_0dc17582_d11d_4a4d_8e25_816d59" +
                        "870ef4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot;?&gt;
        ///&lt;Файл ИдФайл=&quot;ON_NSCHFDOPPR_2LT-600006439_2LT-600003352_20210426_a5011718-844e-4bba-b15c-a1c15e49a691&quot; ВерсФорм=&quot;5.01&quot; ВерсПрог=&quot;EDOLite 1.0&quot;&gt;
        ///    &lt;СвУчДокОбор ИдОтпр=&quot;2LT-600003352&quot; ИдПол=&quot;2LT-600006439&quot;&gt;
        ///        &lt;СвОЭДОтпр НаимОрг=&quot;ООО &amp;quot;Оператор-ЦРПТ&amp;quot;&quot; ИННЮЛ=&quot;7731376812&quot; ИдЭДО=&quot;2LT&quot;/&gt;
        ///    &lt;/СвУчДокОбор&gt;
        ///    &lt;Документ КНД=&quot;1115131&quot; Функция=&quot;СЧФДОП&quot; ПоФактХЖ=&quot;Документ об отгрузке товаров (выполнении работ), передаче имущественных прав (документ об оказ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ON_NSCHFDOPPR_2LT_600006439_2LT_600003352_20210426_a5011718_844e_4bba_b15c_a1c15e49a691_УПДи {
            get {
                return ResourceManager.GetString("ON_NSCHFDOPPR_2LT_600006439_2LT_600003352_20210426_a5011718_844e_4bba_b15c_a1c15e" +
                        "49a691_УПДи", resourceCulture);
            }
        }
    }
}
