//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairMark.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FairMark.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Файл ИдФайл=&quot;ON_NSCHFDOPPRMARK_2LT-600061573_2LT-354_20191121_99933cc4-710d-4a6f-aa1c03203dc8f6c4&quot; ВерсФорм=&quot;5.01&quot; ВерсПрог=&quot;EDOLite 1.0&quot;&gt;
        ///   &lt;СвУчДокОбор ИдОтпр=&quot;2LT-600000078&quot; ИдПол=&quot;2LT-354&quot;&gt;
        ///      &lt;СвОЭДОтпр НаимОрг=&quot;ООО &apos;Оператор-ЦРПТ&apos;&quot; ИННЮЛ=&quot;00000000&quot; ИдЭДО=&quot;2LT&quot; /&gt;
        ///   &lt;/СвУчДокОбор&gt;
        ///   &lt;Документ КНД=&quot;1115131&quot; Функция=&quot;СЧФ&quot; ПоФактХЖ=&quot;Документ об отгрузке товаров (выполнении работ), передаче имущественных прав (документ об оказании услуг)&quot; НаимДокОпр=&quot;Счет- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EdoLite_Chapter_3_1_SampleUpd {
            get {
                return ResourceManager.GetString("EdoLite_Chapter_3_1_SampleUpd", resourceCulture);
            }
        }
    }
}
