//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    /// <summary>
    /// <para>Информация об адресе, в том числе об адресе за пределами территории Российской Федерации</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Информация об адресе, в том числе об адресе за пределами территории Российской Фе" +
        "дерации")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("АдрИнфТип", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрИнфТип
    {
        
        /// <summary>
        /// <para>Код страны</para>
        /// <para>Код из Общероссийского классификатора стран мира</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [0-9]{3}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код страны")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(3)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(3)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{3}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("КодСтр")]
        public string КодСтр { get; set; }
        
        /// <summary>
        /// <para>Адрес</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Адрес")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1000)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("АдрТекст")]
        public string АдрТекст { get; set; }
    }
}
