//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    /// <summary>
    /// <para>Сведения об адресе</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Сведения об адресе")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("АдресТип", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдресТип
    {
        
        /// <summary>
        /// <para>Адрес, указанный в Едином государственном реестре юридических лиц/почтовый адрес/адрес места жительства индивидуального предпринимателя (реквизиты адреса на территории Российской Федерации)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Адрес, указанный в Едином государственном реестре юридических лиц/почтовый адрес/" +
            "адрес места жительства индивидуального предпринимателя (реквизиты адреса на терр" +
            "итории Российской Федерации)")]
        [System.Xml.Serialization.XmlElementAttribute("АдрРФ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public АдрРФТип АдрРФ { get; set; }
        
        /// <summary>
        /// <para>Адрес, указанный в Едином государственном реестре юридических лиц/почтовый адрес/адрес места жительства индивидуального предпринимателя (информация об адресе, в том числе об адресе за пределами территории Российской Федерации)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Адрес, указанный в Едином государственном реестре юридических лиц/почтовый адрес/" +
            "адрес места жительства индивидуального предпринимателя (информация об адресе, в " +
            "том числе об адресе за пределами территории Российской Федерации)")]
        [System.Xml.Serialization.XmlElementAttribute("АдрИнф", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public АдрИнфТип АдрИнф { get; set; }
        
        /// <summary>
        /// <para>Уникальный номер адреса объекта адресации в государственном адресном реестре</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 36.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Уникальный номер адреса объекта адресации в государственном адресном реестре")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(36)]
        [System.Xml.Serialization.XmlElementAttribute("КодГАР", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодГАР { get; set; }
    }
}
