//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    /// <summary>
    /// <para>Сведения об индивидуальном предпринимателе</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Сведения об индивидуальном предпринимателе")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("СвИПТип", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СвИПТип
    {
        
        /// <summary>
        /// <para>Фамилия, имя, отчество</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Фамилия, имя, отчество")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ФИО", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФИОТип ФИО { get; set; }
        
        /// <summary>
        /// <para>ИНН</para>
        /// <para>Идентификационный номер налогоплательщика - физического лица</para>
        /// <para xml:lang="en">Minimum length: 12.</para>
        /// <para xml:lang="en">Maximum length: 12.</para>
        /// <para xml:lang="en">Pattern: ([0-9]{1}[1-9]{1}|[1-9]{1}[0-9]{1})[0-9]{10}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ИНН")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(12)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(12)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([0-9]{1}[1-9]{1}|[1-9]{1}[0-9]{1})[0-9]{10}")]
        [System.Xml.Serialization.XmlAttributeAttribute("ИННФЛ")]
        public string ИННФЛ { get; set; }
        
        /// <summary>
        /// <para>ИНН при составлении документа с Функция=СЧФ или Функция=СЧФДОП налоговым агентом, указанным в пунктах 2 и 3 статьи 161 НК РФ, в части информации о продавце/грузоотправителе</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ИНН при составлении документа с Функция=СЧФ или Функция=СЧФДОП налоговым агентом," +
            " указанным в пунктах 2 и 3 статьи 161 НК РФ, в части информации о продавце/грузо" +
            "отправителе")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1)]
        [System.Xml.Serialization.XmlAttributeAttribute("ДефИННФЛ")]
        public string ДефИННФЛ { get; set; }
        
        /// <summary>
        /// <para>Реквизиты свидетельства о государственной регистрации индивидуального предпринимателя</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Реквизиты свидетельства о государственной регистрации индивидуального предпринима" +
            "теля")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(100)]
        [System.Xml.Serialization.XmlAttributeAttribute("СвГосРегИП")]
        public string СвГосРегИП { get; set; }
        
        /// <summary>
        /// <para>Иные сведения, идентифицирующие физическое лицо</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иные сведения, идентифицирующие физическое лицо")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlAttributeAttribute("ИныеСвед")]
        public string ИныеСвед { get; set; }
    }
}
