//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    /// <summary>
    /// <para>Сумма акциза</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Сумма акциза")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("СумАкцизТип", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СумАкцизТип
    {
        
        /// <summary>
        /// <para>Сумма акциза</para>
        /// <para xml:lang="en">Total number of digits: 19.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сумма акциза")]
        [System.Xml.Serialization.XmlElementAttribute("СумАкциз", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal СумАкциз { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the СумАкциз property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СумАкцизSpecified { get; set; }
        
        /// <summary>
        /// <para>Без акциза</para>
        /// <para xml:lang="en">Minimum length: 10.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Без акциза")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.Xml.Serialization.XmlElementAttribute("БезАкциз", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string БезАкциз { get; set; }
    }
}
