//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("УчастникТипБанкРекв", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class УчастникТипБанкРекв
    {
        
        /// <summary>
        /// <para>Сведения о банке</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сведения о банке")]
        [System.Xml.Serialization.XmlElementAttribute("СвБанк", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public УчастникТипБанкРеквСвБанк СвБанк { get; set; }
        
        /// <summary>
        /// <para>Номер банковского счета</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Номер банковского счета")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.Xml.Serialization.XmlAttributeAttribute("НомерСчета")]
        public string НомерСчета { get; set; }
    }
}
