//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("УчастникТипБанкРеквСвБанк", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class УчастникТипБанкРеквСвБанк
    {
        
        /// <summary>
        /// <para>Наименование банка</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Наименование банка")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1000)]
        [System.Xml.Serialization.XmlAttributeAttribute("НаимБанк")]
        public string НаимБанк { get; set; }
        
        /// <summary>
        /// <para>Банковский идентификационный код (БИК) в соответствии со «Справочником БИК РФ»</para>
        /// <para>БИК банка</para>
        /// <para xml:lang="en">Minimum length: 9.</para>
        /// <para xml:lang="en">Maximum length: 9.</para>
        /// <para xml:lang="en">Pattern: [0-9]{9}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Банковский идентификационный код (БИК) в соответствии со «Справочником БИК РФ»")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(9)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(9)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{9}")]
        [System.Xml.Serialization.XmlAttributeAttribute("БИК")]
        public string БИК { get; set; }
        
        /// <summary>
        /// <para>Корреспондентский счет банка</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Корреспондентский счет банка")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.Xml.Serialization.XmlAttributeAttribute("КорСчет")]
        public string КорСчет { get; set; }
    }
}
