//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    /// <summary>
    /// <para>Сведения об участнике факта хозяйственной жизни</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Сведения об участнике факта хозяйственной жизни")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("УчастникТип", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class УчастникТип
    {
        
        /// <summary>
        /// <para>Идентификационные сведения</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификационные сведения")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ИдСв", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public УчастникТипИдСв ИдСв { get; set; }
        
        /// <summary>
        /// <para>Адрес</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Адрес")]
        [System.Xml.Serialization.XmlElementAttribute("Адрес", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public АдресТип Адрес { get; set; }
        
        /// <summary>
        /// <para>Контактные данные</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Контактные данные")]
        [System.Xml.Serialization.XmlElementAttribute("Контакт", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public КонтактТип Контакт { get; set; }
        
        /// <summary>
        /// <para>Банковские реквизиты</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Банковские реквизиты")]
        [System.Xml.Serialization.XmlElementAttribute("БанкРекв", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public УчастникТипБанкРекв БанкРекв { get; set; }
        
        /// <summary>
        /// <para>Код в общероссийском классификаторе предприятий и организаций</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код в общероссийском классификаторе предприятий и организаций")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.Xml.Serialization.XmlAttributeAttribute("ОКПО")]
        public string ОКПО { get; set; }
        
        /// <summary>
        /// <para>Структурное подразделение</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Структурное подразделение")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1000)]
        [System.Xml.Serialization.XmlAttributeAttribute("СтруктПодр")]
        public string СтруктПодр { get; set; }
        
        /// <summary>
        /// <para>Информация для участника документооборота</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Информация для участника документооборота")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlAttributeAttribute("ИнфДляУчаст")]
        public string ИнфДляУчаст { get; set; }
        
        /// <summary>
        /// <para>Краткое название</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Краткое название")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlAttributeAttribute("КраткНазв")]
        public string КраткНазв { get; set; }
    }
}
