//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлДокументСвСчФактДопСвФХЖ1", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлДокументСвСчФактДопСвФХЖ1
    {
        
        /// <summary>
        /// <para>Информация продавца об обстоятельствах закупок для государственных и муниципальных нужд (для учета Федеральным казначейством денежных обязательств)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Информация продавца об обстоятельствах закупок для государственных и муниципальны" +
            "х нужд (для учета Федеральным казначейством денежных обязательств)")]
        [System.Xml.Serialization.XmlElementAttribute("ИнфПродГосЗакКазн", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвСчФактДопСвФХЖ1ИнфПродГосЗакКазн ИнфПродГосЗакКазн { get; set; }
        
        /// <summary>
        /// <para>Сведения о факторе</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сведения о факторе")]
        [System.Xml.Serialization.XmlElementAttribute("СвФактор", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public УчастникТип СвФактор { get; set; }
        
        /// <summary>
        /// <para>Основание уступки денежного требования</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Основание уступки денежного требования")]
        [System.Xml.Serialization.XmlElementAttribute("ОснУстДенТреб", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ОснованиеТип ОснУстДенТреб { get; set; }
        
        /// <summary>
        /// <para>Идентификатор государственного контракта, договора (соглашения) 
        ///(строка 8 счета-фактуры)</para>
        /// <para xml:lang="en">Minimum length: 20.</para>
        /// <para xml:lang="en">Maximum length: 25.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификатор государственного контракта, договора (соглашения) (строка 8 счета-ф" +
            "актуры)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(20)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(25)]
        [System.Xml.Serialization.XmlAttributeAttribute("ИдГосКон")]
        public string ИдГосКон { get; set; }
        
        /// <summary>
        /// <para>Валюта: Наименование</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Валюта: Наименование")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(100)]
        [System.Xml.Serialization.XmlAttributeAttribute("НаимОКВ")]
        public string НаимОКВ { get; set; }
        
        /// <summary>
        /// <para>Курс валюты</para>
        /// <para xml:lang="en">Total number of digits: 10.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 4.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Курс валюты")]
        [System.Xml.Serialization.XmlAttributeAttribute("КурсВал")]
        public decimal КурсВал { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the КурсВал property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КурсВалSpecified { get; set; }
        
        /// <summary>
        /// <para>Обстоятельства формирования счета-фактуры, применяемого при расчетах по налогу на добавленную стоимость</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Обстоятельства формирования счета-фактуры, применяемого при расчетах по налогу на" +
            " добавленную стоимость")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1)]
        [System.Xml.Serialization.XmlAttributeAttribute("ОбстФормСЧФ")]
        public string ОбстФормСЧФ { get; set; }
    }
}
