//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлДокументСвПродПерСвПер", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлДокументСвПродПерСвПер
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ОснованиеТип> _оснПер;
        
        /// <summary>
        /// <para>Основание отгрузки товаров (передачи результатов работ), передачи  имущественных прав (предъявления оказанных услуг)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Основание отгрузки товаров (передачи результатов работ), передачи имущественных п" +
            "рав (предъявления оказанных услуг)")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ОснПер", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ОснованиеТип> ОснПер
        {
            get
            {
                return this._оснПер;
            }
            private set
            {
                this._оснПер = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ФайлДокументСвПродПерСвПер" /> class.</para>
        /// </summary>
        public ФайлДокументСвПродПерСвПер()
        {
            this._оснПер = new System.Collections.ObjectModel.Collection<ОснованиеТип>();
        }
        
        /// <summary>
        /// <para>Сведения о лице, передавшем товар (груз)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сведения о лице, передавшем товар (груз)")]
        [System.Xml.Serialization.XmlElementAttribute("СвЛицПер", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерСвЛицПер СвЛицПер { get; set; }
        
        /// <summary>
        /// <para>Транспортировка и груз</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Транспортировка и груз")]
        [System.Xml.Serialization.XmlElementAttribute("ТранГруз", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерТранГруз ТранГруз { get; set; }
        
        /// <summary>
        /// <para>Сведения о передаче вещи, изготовленной по договору подряда</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сведения о передаче вещи, изготовленной по договору подряда")]
        [System.Xml.Serialization.XmlElementAttribute("СвПерВещи", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерСвПерВещи СвПерВещи { get; set; }
        
        /// <summary>
        /// <para>Содержание операции</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Содержание операции")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("СодОпер")]
        public string СодОпер { get; set; }
        
        /// <summary>
        /// <para>Вид операции</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Вид операции")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlAttributeAttribute("ВидОпер")]
        public string ВидОпер { get; set; }
        
        /// <summary>
        /// <para>Дата отгрузки товаров (передачи результатов работ), передачи имущественных прав (предъявления оказанных услуг)</para>
        /// <para>Дата в формате ДД.ММ.ГГГГ (01.01.1900 - 31.12.2099)</para>
        /// <para xml:lang="en">Minimum length: 10.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// <para xml:lang="en">Pattern: ((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\.(01|0[3-9]{1}|1[0-2]{1}))|(31\.(01|03|05|07|08|10|12)))\.((19|20)[0-9]{2}))|(29\.02\.((19|20)(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6))))).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Дата отгрузки товаров (передачи результатов работ), передачи имущественных прав (" +
            "предъявления оказанных услуг)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\\.(01|0[3-9]{1" +
            "}|1[0-2]{1}))|(31\\.(01|03|05|07|08|10|12)))\\.((19|20)[0-9]{2}))|(29\\.02\\.((19|20" +
            ")(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6)))))")]
        [System.Xml.Serialization.XmlAttributeAttribute("ДатаПер")]
        public string ДатаПер { get; set; }
        
        /// <summary>
        /// <para>Дата начала периода оказания услуг (выполнения работ, поставки товаров,)</para>
        /// <para>Дата в формате ДД.ММ.ГГГГ (01.01.1900 - 31.12.2099)</para>
        /// <para xml:lang="en">Minimum length: 10.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// <para xml:lang="en">Pattern: ((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\.(01|0[3-9]{1}|1[0-2]{1}))|(31\.(01|03|05|07|08|10|12)))\.((19|20)[0-9]{2}))|(29\.02\.((19|20)(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6))))).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Дата начала периода оказания услуг (выполнения работ, поставки товаров,)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\\.(01|0[3-9]{1" +
            "}|1[0-2]{1}))|(31\\.(01|03|05|07|08|10|12)))\\.((19|20)[0-9]{2}))|(29\\.02\\.((19|20" +
            ")(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6)))))")]
        [System.Xml.Serialization.XmlAttributeAttribute("ДатаНач")]
        public string ДатаНач { get; set; }
        
        /// <summary>
        /// <para>Дата окончания периода оказания услуг (выполнения работ, поставки товаров)</para>
        /// <para>Дата в формате ДД.ММ.ГГГГ (01.01.1900 - 31.12.2099)</para>
        /// <para xml:lang="en">Minimum length: 10.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// <para xml:lang="en">Pattern: ((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\.(01|0[3-9]{1}|1[0-2]{1}))|(31\.(01|03|05|07|08|10|12)))\.((19|20)[0-9]{2}))|(29\.02\.((19|20)(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6))))).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Дата окончания периода оказания услуг (выполнения работ, поставки товаров)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\\.(01|0[3-9]{1" +
            "}|1[0-2]{1}))|(31\\.(01|03|05|07|08|10|12)))\\.((19|20)[0-9]{2}))|(29\\.02\\.((19|20" +
            ")(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6)))))")]
        [System.Xml.Serialization.XmlAttributeAttribute("ДатаОкон")]
        public string ДатаОкон { get; set; }
    }
}
