//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлДокументСвПродПерСвПерСвЛицПер", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлДокументСвПродПерСвПерСвЛицПер
    {
        
        /// <summary>
        /// <para>Работник организации продавца</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Работник организации продавца")]
        [System.Xml.Serialization.XmlElementAttribute("РабОргПрод", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерСвЛицПерРабОргПрод РабОргПрод { get; set; }
        
        /// <summary>
        /// <para>Иное лицо</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иное лицо")]
        [System.Xml.Serialization.XmlElementAttribute("ИнЛицо", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерСвЛицПерИнЛицо ИнЛицо { get; set; }
    }
}
