//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлДокументСвПродПер", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлДокументСвПродПер
    {
        
        /// <summary>
        /// <para>Сведения о передаче (сдаче) товаров (результатов работ), имущественных прав (о предъявлении оказанных услуг)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сведения о передаче (сдаче) товаров (результатов работ), имущественных прав (о пр" +
            "едъявлении оказанных услуг)")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("СвПер", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПер СвПер { get; set; }
        
        /// <summary>
        /// <para>Информационное поле факта хозяйственной жизни 3</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Информационное поле факта хозяйственной жизни 3")]
        [System.Xml.Serialization.XmlElementAttribute("ИнфПолФХЖ3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерИнфПолФХЖ3 ИнфПолФХЖ3 { get; set; }
    }
}
