//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлДокументТаблСчФакт", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлДокументТаблСчФакт
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ФайлДокументТаблСчФактСведТов> _сведТов;
        
        /// <summary>
        /// <para>Сведения об отгруженных товарах (о выполненных работах, оказанных услугах), переданных имущественных правах</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сведения об отгруженных товарах (о выполненных работах, оказанных услугах), перед" +
            "анных имущественных правах")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("СведТов", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ФайлДокументТаблСчФактСведТов> СведТов
        {
            get
            {
                return this._сведТов;
            }
            private set
            {
                this._сведТов = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ФайлДокументТаблСчФакт" /> class.</para>
        /// </summary>
        public ФайлДокументТаблСчФакт()
        {
            this._сведТов = new System.Collections.ObjectModel.Collection<ФайлДокументТаблСчФактСведТов>();
        }
        
        /// <summary>
        /// <para>Реквизиты строки «Всего к оплате»</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Реквизиты строки «Всего к оплате»")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ВсегоОпл", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументТаблСчФактВсегоОпл ВсегоОпл { get; set; }
    }
}
