//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлДокументСвПродПерСвПерСвЛицПерИнЛицоФЛПер", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлДокументСвПродПерСвПерСвЛицПерИнЛицоФЛПер
    {
        
        /// <summary>
        /// <para>Фамилия, имя, отчество</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Фамилия, имя, отчество")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ФИО", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФИОТип ФИО { get; set; }
        
        /// <summary>
        /// <para>Иные сведения, идентифицирующие физическое лицо</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иные сведения, идентифицирующие физическое лицо")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlAttributeAttribute("ИныеСвед")]
        public string ИныеСвед { get; set; }
        
        /// <summary>
        /// <para>Основание, по которому физическому лицу доверена отгрузка товаров (передача результатов работ), передача имущественных прав (предъявление оказанных услуг)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 120.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Основание, по которому физическому лицу доверена отгрузка товаров (передача резул" +
            "ьтатов работ), передача имущественных прав (предъявление оказанных услуг)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(120)]
        [System.Xml.Serialization.XmlAttributeAttribute("ОснДоверФЛ")]
        public string ОснДоверФЛ { get; set; }
    }
}
