//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлДокументТаблСчФактВсегоОпл", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлДокументТаблСчФактВсегоОпл
    {
        
        /// <summary>
        /// <para>Всего к оплате, Сумма налога, предъявляемая покупателю (строка «Всего к оплате»/графа 8 счета-фактуры)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Всего к оплате, Сумма налога, предъявляемая покупателю (строка «Всего к оплате»/г" +
            "рафа 8 счета-фактуры)")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("СумНалВсего", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СумНДСТип СумНалВсего { get; set; }
        
        /// <summary>
        /// <para>Количество (масса нетто/ количество) - всего по документу</para>
        /// <para xml:lang="en">Total number of digits: 26.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 11.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Количество (масса нетто/ количество) - всего по документу")]
        [System.Xml.Serialization.XmlElementAttribute("КолНеттоВс", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal КолНеттоВс { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the КолНеттоВс property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КолНеттоВсSpecified { get; set; }
        
        /// <summary>
        /// <para>Всего к оплате, Стоимость товаров (работ, услуг), имущественных прав без налога - всего (строка «Всего к оплате»/графа 5 счета-фактуры)</para>
        /// <para xml:lang="en">Total number of digits: 19.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Всего к оплате, Стоимость товаров (работ, услуг), имущественных прав без налога -" +
            " всего (строка «Всего к оплате»/графа 5 счета-фактуры)")]
        [System.Xml.Serialization.XmlAttributeAttribute("СтТовБезНДСВсего")]
        public decimal СтТовБезНДСВсего { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the СтТовБезНДСВсего property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтТовБезНДСВсегоSpecified { get; set; }
        
        /// <summary>
        /// <para>Всего к оплате, Стоимость товаров (работ, услуг), имущественных прав с налогом - всего (строка «Всего к оплате»/графа 9 счета-фактуры)</para>
        /// <para xml:lang="en">Total number of digits: 19.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Всего к оплате, Стоимость товаров (работ, услуг), имущественных прав с налогом - " +
            "всего (строка «Всего к оплате»/графа 9 счета-фактуры)")]
        [System.Xml.Serialization.XmlAttributeAttribute("СтТовУчНалВсего")]
        public decimal СтТовУчНалВсего { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the СтТовУчНалВсего property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтТовУчНалВсегоSpecified { get; set; }
        
        /// <summary>
        /// <para>Всего к оплате, Стоимость товаров (работ, услуг), имущественных прав с налогом - всего (строка «Всего к оплате»/графа 9 счета-фактуры) при отсутствии показателя</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Всего к оплате, Стоимость товаров (работ, услуг), имущественных прав с налогом - " +
            "всего (строка «Всего к оплате»/графа 9 счета-фактуры) при отсутствии показателя")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1)]
        [System.Xml.Serialization.XmlAttributeAttribute("ДефСтТовУчНалВсего")]
        public string ДефСтТовУчНалВсего { get; set; }
    }
}
