//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлДокументПодписант", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлДокументПодписант
    {
        
        /// <summary>
        /// <para>Физическое лицо</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Физическое лицо")]
        [System.Xml.Serialization.XmlElementAttribute("ФЛ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СвФЛТип ФЛ { get; set; }
        
        /// <summary>
        /// <para>Индивидуальный предприниматель</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Индивидуальный предприниматель")]
        [System.Xml.Serialization.XmlElementAttribute("ИП", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СвИПТип ИП { get; set; }
        
        /// <summary>
        /// <para>Представитель юридического лица</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Представитель юридического лица")]
        [System.Xml.Serialization.XmlElementAttribute("ЮЛ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументПодписантЮЛ ЮЛ { get; set; }
        
        /// <summary>
        /// <para>Область полномочий</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Область полномочий")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ОблПолн")]
        public string ОблПолн { get; set; }
        
        /// <summary>
        /// <para>Статус</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Статус")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Статус")]
        public string Статус { get; set; }
        
        /// <summary>
        /// <para>Основание полномочий (доверия)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Основание полномочий (доверия)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ОснПолн")]
        public string ОснПолн { get; set; }
        
        /// <summary>
        /// <para>Основание полномочий (доверия) организации</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Основание полномочий (доверия) организации")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlAttributeAttribute("ОснПолнОрг")]
        public string ОснПолнОрг { get; set; }
    }
}
