//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлДокументТаблСчФактСведТовСвТД", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлДокументТаблСчФактСведТовСвТД
    {
        
        /// <summary>
        /// <para>Цифровой код страны происхождения товара (Графа 10 счета-фактуры)</para>
        /// <para>Код из Общероссийского классификатора стран мира</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [0-9]{3}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Цифровой код страны происхождения товара (Графа 10 счета-фактуры)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(3)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(3)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{3}")]
        [System.Xml.Serialization.XmlAttributeAttribute("КодПроисх")]
        public string КодПроисх { get; set; }
        
        /// <summary>
        /// <para>Цифровой код страны происхождения товара (Графа 10 счета-фактуры; для документа с Функция=СЧФ, выставляемом при получении оплаты, частичной оплаты в счет предстоящих поставок товаров (выполнения работ, оказания услуг), передачи имущественных прав</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Цифровой код страны происхождения товара (Графа 10 счета-фактуры; для документа с" +
            " Функция=СЧФ, выставляемом при получении оплаты, частичной оплаты в счет предсто" +
            "ящих поставок товаров (выполнения работ, оказания услуг), передачи имущественных" +
            " прав")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1)]
        [System.Xml.Serialization.XmlAttributeAttribute("ДефКодПроисх")]
        public string ДефКодПроисх { get; set; }
        
        /// <summary>
        /// <para>Регистрационный номер таможенной декларации (номер декларации на товары; графа 11 счета-фактуры)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 29.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Регистрационный номер таможенной декларации (номер декларации на товары; графа 11" +
            " счета-фактуры)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(29)]
        [System.Xml.Serialization.XmlAttributeAttribute("НомерТД")]
        public string НомерТД { get; set; }
    }
}
