//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлСвУчДокОбор", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлСвУчДокОбор
    {
        
        /// <summary>
        /// <para>Сведения об операторе электронного документооборота отправителя файла обмена счета-фактуры (информации продавца)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сведения об операторе электронного документооборота отправителя файла обмена счет" +
            "а-фактуры (информации продавца)")]
        [System.Xml.Serialization.XmlElementAttribute("СвОЭДОтпр", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлСвУчДокОборСвОЭДОтпр СвОЭДОтпр { get; set; }
        
        /// <summary>
        /// <para>Идентификатор участника документооборота – отправителя файла обмена счета-фактуры (информации продавца)</para>
        /// <para xml:lang="en">Minimum length: 4.</para>
        /// <para xml:lang="en">Maximum length: 46.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификатор участника документооборота – отправителя файла обмена счета-фактуры" +
            " (информации продавца)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(4)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(46)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ИдОтпр")]
        public string ИдОтпр { get; set; }
        
        /// <summary>
        /// <para>Идентификатор участника документооборота - получателя файла обмена счета-фактуры (информации продавца)</para>
        /// <para xml:lang="en">Minimum length: 4.</para>
        /// <para xml:lang="en">Maximum length: 46.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификатор участника документооборота - получателя файла обмена счета-фактуры " +
            "(информации продавца)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(4)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(46)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ИдПол")]
        public string ИдПол { get; set; }
    }
}
