//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлДокументТаблСчФактСведТовДопСведТовНомСредИдентТов", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлДокументТаблСчФактСведТовДопСведТовНомСредИдентТов
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _кИЗ;
        
        /// <summary>
        /// <para>Контрольный идентификационный знак</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Контрольный идентификационный знак")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("КИЗ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<string> КИЗ
        {
            get
            {
                return this._кИЗ;
            }
            private set
            {
                this._кИЗ = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the КИЗ collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КИЗSpecified
        {
            get
            {
                return (this.КИЗ.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ФайлДокументТаблСчФактСведТовДопСведТовНомСредИдентТов" /> class.</para>
        /// </summary>
        public ФайлДокументТаблСчФактСведТовДопСведТовНомСредИдентТов()
        {
            this._кИЗ = new System.Collections.ObjectModel.Collection<string>();
            this._номУпак = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _номУпак;
        
        /// <summary>
        /// <para>Уникальный идентификатор вторичной (потребительской)/третичной (заводской, транспортной) упаковки</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Уникальный идентификатор вторичной (потребительской)/третичной (заводской, трансп" +
            "ортной) упаковки")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("НомУпак", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<string> НомУпак
        {
            get
            {
                return this._номУпак;
            }
            private set
            {
                this._номУпак = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the НомУпак collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool НомУпакSpecified
        {
            get
            {
                return (this.НомУпак.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>Уникальный идентификатор транспортной упаковки</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Уникальный идентификатор транспортной упаковки")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlAttributeAttribute("ИдентТрансУпак")]
        public string ИдентТрансУпак { get; set; }
    }
}
