//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлДокументСвПродПерСвПерСвЛицПерИнЛицо", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлДокументСвПродПерСвПерСвЛицПерИнЛицо
    {
        
        /// <summary>
        /// <para>Представитель организации, которой доверена отгрузка товаров (передача результатов работ), передача имущественных прав (предъявление оказанных услуг)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Представитель организации, которой доверена отгрузка товаров (передача результато" +
            "в работ), передача имущественных прав (предъявление оказанных услуг)")]
        [System.Xml.Serialization.XmlElementAttribute("ПредОргПер", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерСвЛицПерИнЛицоПредОргПер ПредОргПер { get; set; }
        
        /// <summary>
        /// <para>Физическое лицо, которому доверена отгрузка товаров (передача результатов работ), передача имущественных прав (предъявление оказанных услуг)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Физическое лицо, которому доверена отгрузка товаров (передача результатов работ)," +
            " передача имущественных прав (предъявление оказанных услуг)")]
        [System.Xml.Serialization.XmlElementAttribute("ФЛПер", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерСвЛицПерИнЛицоФЛПер ФЛПер { get; set; }
    }
}
