//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлДокументТаблСчФактСведТовДопСведТов", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлДокументТаблСчФактСведТовДопСведТов
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ФайлДокументТаблСчФактСведТовДопСведТовСведПрослеж> _сведПрослеж;
        
        /// <summary>
        /// <para>Сведения о товаре, подлежащем прослеживаемости</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сведения о товаре, подлежащем прослеживаемости")]
        [System.Xml.Serialization.XmlElementAttribute("СведПрослеж", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ФайлДокументТаблСчФактСведТовДопСведТовСведПрослеж> СведПрослеж
        {
            get
            {
                return this._сведПрослеж;
            }
            private set
            {
                this._сведПрослеж = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the СведПрослеж collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СведПрослежSpecified
        {
            get
            {
                return (this.СведПрослеж.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ФайлДокументТаблСчФактСведТовДопСведТов" /> class.</para>
        /// </summary>
        public ФайлДокументТаблСчФактСведТовДопСведТов()
        {
            this._сведПрослеж = new System.Collections.ObjectModel.Collection<ФайлДокументТаблСчФактСведТовДопСведТовСведПрослеж>();
            this._номСредИдентТов = new System.Collections.ObjectModel.Collection<ФайлДокументТаблСчФактСведТовДопСведТовНомСредИдентТов>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ФайлДокументТаблСчФактСведТовДопСведТовНомСредИдентТов> _номСредИдентТов;
        
        /// <summary>
        /// <para>Номер средств идентификации товаров</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Номер средств идентификации товаров")]
        [System.Xml.Serialization.XmlElementAttribute("НомСредИдентТов", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ФайлДокументТаблСчФактСведТовДопСведТовНомСредИдентТов> НомСредИдентТов
        {
            get
            {
                return this._номСредИдентТов;
            }
            private set
            {
                this._номСредИдентТов = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the НомСредИдентТов collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool НомСредИдентТовSpecified
        {
            get
            {
                return (this.НомСредИдентТов.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>Признак Товар/Работа/Услуга/Право/Иное</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Признак Товар/Работа/Услуга/Право/Иное")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1)]
        [System.Xml.Serialization.XmlAttributeAttribute("ПрТовРаб")]
        public string ПрТовРаб { get; set; }
        
        /// <summary>
        /// <para>Дополнительная информация о признаке</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 4.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Дополнительная информация о признаке")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4)]
        [System.Xml.Serialization.XmlAttributeAttribute("ДопПризн")]
        public string ДопПризн { get; set; }
        
        /// <summary>
        /// <para>Наименование единицы измерения (условное обозначение национальное, графа 2а счета-фактуры)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Наименование единицы измерения (условное обозначение национальное, графа 2а счета" +
            "-фактуры)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlAttributeAttribute("НаимЕдИзм")]
        public string НаимЕдИзм { get; set; }
        
        /// <summary>
        /// <para>Краткое наименование страны происхождения товара (графа 10а счета-фактуры)/страна регистрации производителя товара</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Краткое наименование страны происхождения товара (графа 10а счета-фактуры)/страна" +
            " регистрации производителя товара")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlAttributeAttribute("КрНаимСтрПр")]
        public string КрНаимСтрПр { get; set; }
        
        /// <summary>
        /// <para>Заказанное количество (количество надлежит отпустить)</para>
        /// <para xml:lang="en">Total number of digits: 26.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 11.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Заказанное количество (количество надлежит отпустить)")]
        [System.Xml.Serialization.XmlAttributeAttribute("НадлОтп")]
        public decimal НадлОтп { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the НадлОтп property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool НадлОтпSpecified { get; set; }
        
        /// <summary>
        /// <para>Характеристика/описание товара (в том числе графа 1 счета-фактуры)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Характеристика/описание товара (в том числе графа 1 счета-фактуры)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1000)]
        [System.Xml.Serialization.XmlAttributeAttribute("ХарактерТов")]
        public string ХарактерТов { get; set; }
        
        /// <summary>
        /// <para>Сорт товара</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сорт товара")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.Xml.Serialization.XmlAttributeAttribute("СортТов")]
        public string СортТов { get; set; }
        
        /// <summary>
        /// <para>Артикул товара (в том числе графа 1 счета-фактуры)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Артикул товара (в том числе графа 1 счета-фактуры)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlAttributeAttribute("АртикулТов")]
        public string АртикулТов { get; set; }
        
        /// <summary>
        /// <para>Код товара (в том числе графа 1 счета-фактуры)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код товара (в том числе графа 1 счета-фактуры)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(100)]
        [System.Xml.Serialization.XmlAttributeAttribute("КодТов")]
        public string КодТов { get; set; }
        
        /// <summary>
        /// <para>Код каталога</para>
        /// <para xml:lang="en">Minimum length: 27.</para>
        /// <para xml:lang="en">Maximum length: 27.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код каталога")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(27)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(27)]
        [System.Xml.Serialization.XmlAttributeAttribute("КодКат")]
        public string КодКат { get; set; }
        
        /// <summary>
        /// <para>Код вида товара</para>
        /// <para xml:lang="en">Minimum length: 10.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код вида товара")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.Xml.Serialization.XmlAttributeAttribute("КодВидТов")]
        public string КодВидТов { get; set; }
    }
}
