//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлДокументСвСчФактДопСвФХЖ1ИнфПродГосЗакКазн", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлДокументСвСчФактДопСвФХЖ1ИнфПродГосЗакКазн
    {
        
        /// <summary>
        /// <para>Дата государственного контракта</para>
        /// <para>Дата в формате ДД.ММ.ГГГГ (01.01.1900 - 31.12.2099)</para>
        /// <para xml:lang="en">Minimum length: 10.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// <para xml:lang="en">Pattern: ((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\.(01|0[3-9]{1}|1[0-2]{1}))|(31\.(01|03|05|07|08|10|12)))\.((19|20)[0-9]{2}))|(29\.02\.((19|20)(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6))))).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Дата государственного контракта")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\\.(01|0[3-9]{1" +
            "}|1[0-2]{1}))|(31\\.(01|03|05|07|08|10|12)))\\.((19|20)[0-9]{2}))|(29\\.02\\.((19|20" +
            ")(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6)))))")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ДатаГосКонт")]
        public string ДатаГосКонт { get; set; }
        
        /// <summary>
        /// <para>Номер государственного контракта</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Номер государственного контракта")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(100)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("НомерГосКонт")]
        public string НомерГосКонт { get; set; }
        
        /// <summary>
        /// <para>Номер лицевого счета продавца</para>
        /// <para xml:lang="en">Minimum length: 11.</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Номер лицевого счета продавца")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.Xml.Serialization.XmlAttributeAttribute("ЛицСчетПрод")]
        public string ЛицСчетПрод { get; set; }
        
        /// <summary>
        /// <para>Код по бюджетной классификации (продавец)</para>
        /// <para xml:lang="en">Minimum length: 20.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код по бюджетной классификации (продавец)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(20)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.Xml.Serialization.XmlAttributeAttribute("КодПродБюджКласс")]
        public string КодПродБюджКласс { get; set; }
        
        /// <summary>
        /// <para>Код цели (продавец)</para>
        /// <para xml:lang="en">Minimum length: 20.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код цели (продавец)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(20)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.Xml.Serialization.XmlAttributeAttribute("КодЦелиПрод")]
        public string КодЦелиПрод { get; set; }
        
        /// <summary>
        /// <para>Код территориального органа Федерального казначейства продавца</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 4.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код территориального органа Федерального казначейства продавца")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4)]
        [System.Xml.Serialization.XmlAttributeAttribute("КодКазначПрод")]
        public string КодКазначПрод { get; set; }
        
        /// <summary>
        /// <para>Наименование территориального органа Федерального казначейства продавца</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Наименование территориального органа Федерального казначейства продавца")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.Xml.Serialization.XmlAttributeAttribute("НаимКазначПрод")]
        public string НаимКазначПрод { get; set; }
    }
}
