//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлДокументСвПродПерСвПерТранГруз", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлДокументСвПродПерСвПерТранГруз
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ФайлДокументСвПродПерСвПерТранГрузТранНакл> _транНакл;
        
        /// <summary>
        /// <para>Транспортная накладная</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Транспортная накладная")]
        [System.Xml.Serialization.XmlElementAttribute("ТранНакл", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ФайлДокументСвПродПерСвПерТранГрузТранНакл> ТранНакл
        {
            get
            {
                return this._транНакл;
            }
            private set
            {
                this._транНакл = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ТранНакл collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ТранНаклSpecified
        {
            get
            {
                return (this.ТранНакл.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ФайлДокументСвПродПерСвПерТранГруз" /> class.</para>
        /// </summary>
        public ФайлДокументСвПродПерСвПерТранГруз()
        {
            this._транНакл = new System.Collections.ObjectModel.Collection<ФайлДокументСвПродПерСвПерТранГрузТранНакл>();
        }
        
        /// <summary>
        /// <para>Перевозчик</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Перевозчик")]
        [System.Xml.Serialization.XmlElementAttribute("Перевозчик", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public УчастникТип Перевозчик { get; set; }
        
        /// <summary>
        /// <para>Сведения о транспортировке и грузе</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сведения о транспортировке и грузе")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1000)]
        [System.Xml.Serialization.XmlAttributeAttribute("СвТранГруз")]
        public string СвТранГруз { get; set; }
    }
}
