//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPOK
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлИнфПокИнфПокГосЗакКазн", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлИнфПокИнфПокГосЗакКазн
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ФайлИнфПокИнфПокГосЗакКазнИнфСведДенОбяз> _инфСведДенОбяз;
        
        /// <summary>
        /// <para>Информация для сведений о денежном обязательстве</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Информация для сведений о денежном обязательстве")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ИнфСведДенОбяз", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ФайлИнфПокИнфПокГосЗакКазнИнфСведДенОбяз> ИнфСведДенОбяз
        {
            get
            {
                return this._инфСведДенОбяз;
            }
            private set
            {
                this._инфСведДенОбяз = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ФайлИнфПокИнфПокГосЗакКазн" /> class.</para>
        /// </summary>
        public ФайлИнфПокИнфПокГосЗакКазн()
        {
            this._инфСведДенОбяз = new System.Collections.ObjectModel.Collection<ФайлИнфПокИнфПокГосЗакКазнИнфСведДенОбяз>();
        }
        
        /// <summary>
        /// <para>Идентификационный код закупки</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 36.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификационный код закупки")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(36)]
        [System.Xml.Serialization.XmlAttributeAttribute("ИдКодЗак")]
        public string ИдКодЗак { get; set; }
        
        /// <summary>
        /// <para>Номер лицевого счета покупателя</para>
        /// <para xml:lang="en">Minimum length: 11.</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Номер лицевого счета покупателя")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ЛицСчетПок")]
        public string ЛицСчетПок { get; set; }
        
        /// <summary>
        /// <para>Наименование финансового органа покупателя</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Наименование финансового органа покупателя")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("НаимФинОргПок")]
        public string НаимФинОргПок { get; set; }
        
        /// <summary>
        /// <para>Номер реестровой записи покупателя по Реестру участников бюджетного процесса, а также юридических лиц, не являющихся участниками бюджетного процесса</para>
        /// <para xml:lang="en">Minimum length: 8.</para>
        /// <para xml:lang="en">Maximum length: 8.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Номер реестровой записи покупателя по Реестру участников бюджетного процесса, а т" +
            "акже юридических лиц, не являющихся участниками бюджетного процесса")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(8)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(8)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("НомРеестрЗапПок")]
        public string НомРеестрЗапПок { get; set; }
        
        /// <summary>
        /// <para>Учетный номер бюджетного обязательства покупателя</para>
        /// <para xml:lang="en">Minimum length: 16.</para>
        /// <para xml:lang="en">Maximum length: 19.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Учетный номер бюджетного обязательства покупателя")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(16)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(19)]
        [System.Xml.Serialization.XmlAttributeAttribute("УчНомБюдОбязПок")]
        public string УчНомБюдОбязПок { get; set; }
        
        /// <summary>
        /// <para>Код территориального органа Федерального казначейства покупателя</para>
        /// <para xml:lang="en">Minimum length: 4.</para>
        /// <para xml:lang="en">Maximum length: 4.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код территориального органа Федерального казначейства покупателя")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(4)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4)]
        [System.Xml.Serialization.XmlAttributeAttribute("КодКазначПок")]
        public string КодКазначПок { get; set; }
        
        /// <summary>
        /// <para>Наименование территориального органа Федерального казначейства покупателя</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Наименование территориального органа Федерального казначейства покупателя")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.Xml.Serialization.XmlAttributeAttribute("НаимКазначПок")]
        public string НаимКазначПок { get; set; }
        
        /// <summary>
        /// <para>Код покупателя в Общероссийском классификаторе территорий муниципальных образований</para>
        /// <para>Код из Общероссийского классификатора территорий муниципальных образований</para>
        /// <para xml:lang="en">Minimum length: 8.</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// <para xml:lang="en">Pattern: ([0-9]{8})|([0-9]{11}).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код покупателя в Общероссийском классификаторе территорий муниципальных образован" +
            "ий")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(8)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([0-9]{8})|([0-9]{11})")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ОКТМОПок")]
        public string ОКТМОПок { get; set; }
        
        /// <summary>
        /// <para>Код места поставки в Общероссийском классификаторе территорий муниципальных образований</para>
        /// <para>Код из Общероссийского классификатора территорий муниципальных образований</para>
        /// <para xml:lang="en">Minimum length: 8.</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// <para xml:lang="en">Pattern: ([0-9]{8})|([0-9]{11}).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код места поставки в Общероссийском классификаторе территорий муниципальных образ" +
            "ований")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(8)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([0-9]{8})|([0-9]{11})")]
        [System.Xml.Serialization.XmlAttributeAttribute("ОКТМОМесПост")]
        public string ОКТМОМесПост { get; set; }
        
        /// <summary>
        /// <para>Предельная дата оплаты</para>
        /// <para>Дата в формате ДД.ММ.ГГГГ (01.01.1900 - 31.12.2099)</para>
        /// <para xml:lang="en">Minimum length: 10.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// <para xml:lang="en">Pattern: ((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\.(01|0[3-9]{1}|1[0-2]{1}))|(31\.(01|03|05|07|08|10|12)))\.((19|20)[0-9]{2}))|(29\.02\.((19|20)(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6))))).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Предельная дата оплаты")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\\.(01|0[3-9]{1" +
            "}|1[0-2]{1}))|(31\\.(01|03|05|07|08|10|12)))\\.((19|20)[0-9]{2}))|(29\\.02\\.((19|20" +
            ")(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6)))))")]
        [System.Xml.Serialization.XmlAttributeAttribute("ДатаОплПред")]
        public string ДатаОплПред { get; set; }
        
        /// <summary>
        /// <para>Учетный номер денежного обязательства</para>
        /// <para xml:lang="en">Minimum length: 22.</para>
        /// <para xml:lang="en">Maximum length: 22.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Учетный номер денежного обязательства")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(22)]
        [System.Xml.Serialization.XmlAttributeAttribute("УчНомДенОбяз")]
        public string УчНомДенОбяз { get; set; }
        
        /// <summary>
        /// <para>Очередность платежа</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Очередность платежа")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1)]
        [System.Xml.Serialization.XmlAttributeAttribute("ОчерПлат")]
        public string ОчерПлат { get; set; }
        
        /// <summary>
        /// <para>Вид платежа</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Вид платежа")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1)]
        [System.Xml.Serialization.XmlAttributeAttribute("ВидПлат")]
        public string ВидПлат { get; set; }
    }
}
