//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPOK
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлИнфПокСодФХЖ4СвПринСвЛицПрин", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлИнфПокСодФХЖ4СвПринСвЛицПрин
    {
        
        /// <summary>
        /// <para>Работник организации покупателя</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Работник организации покупателя")]
        [System.Xml.Serialization.XmlElementAttribute("РабОргПок", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлИнфПокСодФХЖ4СвПринСвЛицПринРабОргПок РабОргПок { get; set; }
        
        /// <summary>
        /// <para>Иное лицо</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иное лицо")]
        [System.Xml.Serialization.XmlElementAttribute("ИнЛицо", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлИнфПокСодФХЖ4СвПринСвЛицПринИнЛицо ИнЛицо { get; set; }
    }
}
