//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPOK
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлИнфПокСодФХЖ4СвПринСвЛицПринИнЛицо", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлИнфПокСодФХЖ4СвПринСвЛицПринИнЛицо
    {
        
        /// <summary>
        /// <para>Представитель организации, которой доверено принятие товаров (груза)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Представитель организации, которой доверено принятие товаров (груза)")]
        [System.Xml.Serialization.XmlElementAttribute("ПредОргПрин", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлИнфПокСодФХЖ4СвПринСвЛицПринИнЛицоПредОргПрин ПредОргПрин { get; set; }
        
        /// <summary>
        /// <para>Физическое лицо, которому доверено принятие товаров (груза)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Физическое лицо, которому доверено принятие товаров (груза)")]
        [System.Xml.Serialization.XmlElementAttribute("ФЛПрин", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлИнфПокСодФХЖ4СвПринСвЛицПринИнЛицоФЛПрин ФЛПрин { get; set; }
    }
}
