//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPOK
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлИнфПокСодФХЖ4", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлИнфПокСодФХЖ4
    {
        
        /// <summary>
        /// <para>Сведения о принятии товаров (результатов выполненных работ), имущественных прав (о подтверждении факта оказания услуг)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сведения о принятии товаров (результатов выполненных работ), имущественных прав (" +
            "о подтверждении факта оказания услуг)")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("СвПрин", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлИнфПокСодФХЖ4СвПрин СвПрин { get; set; }
        
        /// <summary>
        /// <para>Информационное поле факта хозяйственной жизни 4</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Информационное поле факта хозяйственной жизни 4")]
        [System.Xml.Serialization.XmlElementAttribute("ИнфПолФХЖ4", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлИнфПокСодФХЖ4ИнфПолФХЖ4 ИнфПолФХЖ4 { get; set; }
        
        /// <summary>
        /// <para>Наименование первичного документа, согласованное сторонами сделки</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Наименование первичного документа, согласованное сторонами сделки")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("НаимДокОпрПр")]
        public string НаимДокОпрПр { get; set; }
        
        /// <summary>
        /// <para>Функция</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 6.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Функция")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(6)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Функция")]
        public string Функция { get; set; }
        
        /// <summary>
        /// <para>Номер счета-фактуры (информации продавца)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Номер счета-фактуры (информации продавца)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1000)]
        [System.Xml.Serialization.XmlAttributeAttribute("НомСчФИнфПр")]
        public string НомСчФИнфПр { get; set; }
        
        /// <summary>
        /// <para>Дата составления (выписки) счета-фактуры (информации продавца)</para>
        /// <para>Дата в формате ДД.ММ.ГГГГ (01.01.1900 - 31.12.2099)</para>
        /// <para xml:lang="en">Minimum length: 10.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// <para xml:lang="en">Pattern: ((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\.(01|0[3-9]{1}|1[0-2]{1}))|(31\.(01|03|05|07|08|10|12)))\.((19|20)[0-9]{2}))|(29\.02\.((19|20)(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6))))).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Дата составления (выписки) счета-фактуры (информации продавца)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\\.(01|0[3-9]{1" +
            "}|1[0-2]{1}))|(31\\.(01|03|05|07|08|10|12)))\\.((19|20)[0-9]{2}))|(29\\.02\\.((19|20" +
            ")(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6)))))")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ДатаСчФИнфПр")]
        public string ДатаСчФИнфПр { get; set; }
        
        /// <summary>
        /// <para>Вид операции</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Вид операции")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlAttributeAttribute("ВидОперации")]
        public string ВидОперации { get; set; }
    }
}
