//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPOK
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлИнфПокИнфПокГосЗакКазнИнфСведДенОбяз", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлИнфПокИнфПокГосЗакКазнИнфСведДенОбяз
    {
        
        /// <summary>
        /// <para>Номер строки таблицы информации продавца</para>
        /// <para xml:lang="en">Total number of digits: 6.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Номер строки таблицы информации продавца")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("НомСтр")]
        public int НомСтр { get; set; }
        
        /// <summary>
        /// <para>Код объекта капитального строительства федеральной адресной инвестиционной программы/код мероприятия по информатизации</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 24.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код объекта капитального строительства федеральной адресной инвестиционной програ" +
            "ммы/код мероприятия по информатизации")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(24)]
        [System.Xml.Serialization.XmlAttributeAttribute("КодОбъектФАИП")]
        public string КодОбъектФАИП { get; set; }
        
        /// <summary>
        /// <para>Вид средств</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Вид средств")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ВидСредств")]
        public string ВидСредств { get; set; }
        
        /// <summary>
        /// <para>Код по бюджетной классификации (покупатель)</para>
        /// <para xml:lang="en">Minimum length: 20.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код по бюджетной классификации (покупатель)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(20)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("КодПокБюджКласс")]
        public string КодПокБюджКласс { get; set; }
        
        /// <summary>
        /// <para>Код цели (покупатель)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код цели (покупатель)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.Xml.Serialization.XmlAttributeAttribute("КодЦелиПокуп")]
        public string КодЦелиПокуп { get; set; }
        
        /// <summary>
        /// <para>Сумма перечисленного аванса</para>
        /// <para xml:lang="en">Total number of digits: 19.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сумма перечисленного аванса")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("СумАванс")]
        public decimal СумАванс { get; set; }
    }
}
