//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPOK
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлИнфПок", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлИнфПок
    {
        
        /// <summary>
        /// <para>Идентификация файла обмена счета-фактуры (информации продавца) или файла обмена информации продавца</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификация файла обмена счета-фактуры (информации продавца) или файла обмена и" +
            "нформации продавца")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ИдИнфПрод", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлИнфПокИдИнфПрод ИдИнфПрод { get; set; }
        
        /// <summary>
        /// <para>Содержание факта хозяйственной жизни 4 - сведения о принятии товаров (результатов выполненных работ), имущественных прав (о подтверждении факта оказания услуг)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Содержание факта хозяйственной жизни 4 - сведения о принятии товаров (результатов" +
            " выполненных работ), имущественных прав (о подтверждении факта оказания услуг)")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("СодФХЖ4", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлИнфПокСодФХЖ4 СодФХЖ4 { get; set; }
        
        /// <summary>
        /// <para>Информация покупателя об обстоятельствах закупок для государственных и муниципальных нужд (для учета Федеральным казначейством денежных обязательств)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Информация покупателя об обстоятельствах закупок для государственных и муниципаль" +
            "ных нужд (для учета Федеральным казначейством денежных обязательств)")]
        [System.Xml.Serialization.XmlElementAttribute("ИнфПокГосЗакКазн", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлИнфПокИнфПокГосЗакКазн ИнфПокГосЗакКазн { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ФайлИнфПокПодписант> _подписант;
        
        /// <summary>
        /// <para>Сведения о лице, подписывающем файл обмена информации покупателя в электронной форме</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сведения о лице, подписывающем файл обмена информации покупателя в электронной фо" +
            "рме")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Подписант", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ФайлИнфПокПодписант> Подписант
        {
            get
            {
                return this._подписант;
            }
            private set
            {
                this._подписант = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ФайлИнфПок" /> class.</para>
        /// </summary>
        public ФайлИнфПок()
        {
            this._подписант = new System.Collections.ObjectModel.Collection<ФайлИнфПокПодписант>();
        }
        
        /// <summary>
        /// <para>Код документа  по КНД</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код документа по КНД")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("КНД")]
        public ФайлИнфПокКНД КНД { get; set; }
        
        /// <summary>
        /// <para>Дата формирования файла обмена информации покупателя</para>
        /// <para>Дата в формате ДД.ММ.ГГГГ (01.01.1900 - 31.12.2099)</para>
        /// <para xml:lang="en">Minimum length: 10.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// <para xml:lang="en">Pattern: ((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\.(01|0[3-9]{1}|1[0-2]{1}))|(31\.(01|03|05|07|08|10|12)))\.((19|20)[0-9]{2}))|(29\.02\.((19|20)(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6))))).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Дата формирования файла обмена информации покупателя")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\\.(01|0[3-9]{1" +
            "}|1[0-2]{1}))|(31\\.(01|03|05|07|08|10|12)))\\.((19|20)[0-9]{2}))|(29\\.02\\.((19|20" +
            ")(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6)))))")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ДатаИнфПок")]
        public string ДатаИнфПок { get; set; }
        
        /// <summary>
        /// <para>Время формирования файла обмена информации покупателя</para>
        /// <para>Время в формате ЧЧ.ММ.СС</para>
        /// <para xml:lang="en">Minimum length: 8.</para>
        /// <para xml:lang="en">Maximum length: 8.</para>
        /// <para xml:lang="en">Pattern: ([0-1]{1}[0-9]{1}|2[0-3]{1})\.([0-5]{1}[0-9]{1})\.([0-5]{1}[0-9]{1}).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Время формирования файла обмена информации покупателя")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(8)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(8)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([0-1]{1}[0-9]{1}|2[0-3]{1})\\.([0-5]{1}[0-9]{1})\\.([0-5]{1}[0-9]{1})")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ВремИнфПок")]
        public string ВремИнфПок { get; set; }
        
        /// <summary>
        /// <para>Наименование экономического субъекта – составителя файла обмена информации покупателя</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Наименование экономического субъекта – составителя файла обмена информации покупа" +
            "теля")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1000)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("НаимЭконСубСост")]
        public string НаимЭконСубСост { get; set; }
        
        /// <summary>
        /// <para>Основание, по которому экономический субъект является составителем файла обмена информации покупателя</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 120.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Основание, по которому экономический субъект является составителем файла обмена и" +
            "нформации покупателя")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(120)]
        [System.Xml.Serialization.XmlAttributeAttribute("ОснДоверОргСост")]
        public string ОснДоверОргСост { get; set; }
    }
}
