//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace FairMark.Xsd.ON_NSCHFDOPPOK
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ФайлИнфПокСодФХЖ4СвПринСвЛицПринИнЛицоПредОргПрин", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФайлИнфПокСодФХЖ4СвПринСвЛицПринИнЛицоПредОргПрин
    {
        
        /// <summary>
        /// <para>Фамилия, имя, отчество</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Фамилия, имя, отчество")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ФИО", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФИОТип ФИО { get; set; }
        
        /// <summary>
        /// <para>Должность</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 128.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Должность")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(128)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Должность")]
        public string Должность { get; set; }
        
        /// <summary>
        /// <para>Иные сведения, идентифицирующие физическое лицо</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иные сведения, идентифицирующие физическое лицо")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlAttributeAttribute("ИныеСвед")]
        public string ИныеСвед { get; set; }
        
        /// <summary>
        /// <para>Наименование организации</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 128.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Наименование организации")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(128)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("НаимОргПрин")]
        public string НаимОргПрин { get; set; }
        
        /// <summary>
        /// <para>Основание, по которому организации доверено принятие товаров (груза)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 120.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Основание, по которому организации доверено принятие товаров (груза)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(120)]
        [System.Xml.Serialization.XmlAttributeAttribute("ОснДоверОргПрин")]
        public string ОснДоверОргПрин { get; set; }
        
        /// <summary>
        /// <para>Основание полномочий представителя организации на принятие товаров (груза)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 120.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Основание полномочий представителя организации на принятие товаров (груза)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(120)]
        [System.Xml.Serialization.XmlAttributeAttribute("ОснПолнПредПрин")]
        public string ОснПолнПредПрин { get; set; }
    }
}
